#ifndef FILE_INTEGRITY_MONITORING_FILTER_KERNEL_COMM_INFO_H
#define FILE_INTEGRITY_MONITORING_FILTER_KERNEL_COMM_INFO_H

#include <fltKernel.h>
#include "communication_info.h"

#endif //FILE_INTEGRITY_MONITORING_FILTER_KERNEL_COMM_INFO_H