#ifndef FILE_INTEGRITY_MONITORING_FILTER_SENDER_H
#define FILE_INTEGRITY_MONITORING_FILTER_SENDER_H

#include <fltKernel.h>

VOID run_sender(_In_ PVOID pContext);

#endif //FILE_INTEGRITY_MONITORING_FILTER_SENDER_H